### ISSUE TITLE
shell-wrapper lingers

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/saga-python#379]
Dear list,

We are using SLURM + python/saga connector. When a job submitted to
SLURM through saga is done, we still see hanging processes, e.g.:

```
user1   23473  0.0  0.0 113252  3200 ?        S    oct04   0:00 /bin/sh /home/user1/.saga/adaptors/shell_job/wrapper.sh 23449
user2   24274  0.0  0.0 113252  3196 ?        S    oct04   0:00 /bin/sh /home/user2/.saga/adaptors/shell_job/wrapper.sh 24250
user1   28031  0.0  0.1  44392  4136 ?        Ss   oct03   0:00 /usr/lib/systemd/systemd --user
user2   28239  0.0  0.1  44392  4028 ?        Ss   oct03   0:00 /usr/lib/systemd/systemd --user
```
Why this is happening and finished (done) processes are still
appearing (hanging) in the system?
on a server side we use fedora 20 and saga-python 0.20.

Thanks a lot,
Anna

**Comment by kernelt** [comment]
I am working together with Anna and this issue is still exists in our servers. We use fedora 20-21 with saga-python 0.22-0.27. Thanks.

**Comment by andre-merzky** [comment]
Thanks -- I'll pull up a fedora VM on EC2, lets see if I can reproduce it...

**Comment by andre-merzky** [comment]
I am afraid I still can't reproduce it :(

Does the same actually happen with the canonical:

```
            js = saga.job.Service('slurm+ssh://%s' % REMOTE_HOST, session=session)
            jd = saga.job.Description()
            jd.executable = "sleep"
            jd.arguments = ["5s"]
```

(all else being equal)?

**Comment by kernelt** [comment]
Hi Andre. 
I just checked it again on fedora 22 and saga 0.29. Now, It seems to work properly if we use a "pure" saga only (a stand-alone script). However, in our case we use saga via celery - distributed task queue manager. And there problem still exists. I think it is not connected directly to saga. Do you have any ideas what it may be: too many processes (one process for every task)?

**Comment by andre-merzky** [comment]
Hey :)

Would  you mind posting the SAGA part of your celery code?  One thing you may want to be careful about is to reuse the `saga.Session` and, if possible,  the `saga.job.Service` objects, instead of creating new ones every time you need them.

Best, Andre.

**Comment by kernelt** [comment]
Hi Andre.
Now the wrapper.sh process is not hanging. it is not even showing up in system processes during task execution
```
3252  3200 ?        S    oct04   0:00 /bin/sh /home/user1/.saga/adaptors/shell_job/wrapper.sh
```

Currently the processes that hanging after task has been submitted via saga adapter are changed to: 
```
root     26639  0.0  0.0  76576  7228 pts/3    Ss+  авг02   0:01 /usr/bin/ssh -t -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_root_%h_%p.user1.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 user1@ip1
root     26640  0.0  0.1 161972  8332 ?        Ss   авг02   0:00 sshd: user1 [priv]
user1    26646  0.0  0.0  55160  4836 ?        Ss   авг02   0:01 /usr/lib/systemd/systemd --user
user1    26647  0.0  0.0 183752  1628 ?        S    авг02   0:00 (sd-pam)
user1    26649  0.0  0.0 161972  4632 ?        S    авг02   0:01 sshd: user1@pts/4
user1    26650  0.0  0.0 129544  3728 pts/4    Ss+  авг02   0:00 -bash
root     26709  0.0  0.0 160840  4320 pts/7    Ss+  авг02   0:00 /usr/bin/sftp -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_root_%h_%p.user1.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 user1@ip1
root     26710  0.0  0.0  74368  6000 pts/7    S+   авг02   0:00 /usr/bin/ssh -oForwardX11 no -oForwardAgent no -oPermitLocalCommand no -oClearAllForwardings yes -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_root_%h_%p.user1.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -l user1 -oProtocol 2 -s -- ip1 sftp
user1    26711  0.0  0.0  63456  3760 ?        Ss   авг02   0:00 /usr/libexec/openssh/sftp-server
```
These new processes start hanging even after only one user submit task. 



In our current case each user is supposed to a submit task in session with a different context (userid and password),  so we can identify different users in slurm statistics and differentiate them. For each task a saga.job.service and saga.job.description are created. After task is completed the job.service get closed.

Should we reuse session instead of recreating new one every time? Could you suggest how to reuse session with keeping context different? Or how to differentiate and identify sessions which are completed and have to be killed, rather than those which are running and have to be left alive?

Overall task start process is following: web2py -> celery -> saga -> slurm -> node

Any idea what can be causing it?

**Comment by kernelt** [comment]
Hi all.
We fixed it. The problem was in celery and in his own processes.

**Comment by andre-merzky** [comment]
I am so glad you did!  I was  trying to reproduce the stack, but could not...  Thanks for the ping back, happy that this item falls of the TODO list then! :D
