### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by zonca** [radical-cybertools/saga-python#399]
Is there a plan to support Python 3 in the next future?

**Comment by ostrokach** [comment]
I would like this feature as well. Use-cases include running saga inside an IPython notebook and django webserver (all running Python 3).

**Comment by mehdisadeghi** [comment]
Since I have used saga in the past, I would like to incorporate it into some new projects as a library, however, new projects are supposed to be written in py3, so py2 dependency is a no go. Py2 will deprecate in [less than three years](https://pythonclock.org/).

**Comment by andre-merzky** [comment]
We still have three years, right?  Great! :-D 

More seriously: that transition probably makes sense, even if there is not much incentive to prioritize this in our own group right now.  #575  is open since quite a while (and probably out of date by now), but we are missing willing testers and contributors.  Are you interested? :)

Best, Andre.

**Comment by mehdisadeghi** [comment]
> We still have three years, right? Great! :-D

We'll reach there soooon :)

Anyway, good to know about the other issue. When I get there I'll give SAGA some love :)

**Comment by mturilli** [comment]
Porting to start in June 2019.
