### ISSUE TITLE
use _set_session() / get_session() in all adaptors

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/saga-python#480]
see #477/#479

**Comment by mehdisadeghi** [comment]
Hey Andre,

Please see the above commit. I think if we add `session` as a property to the CPI base class, it will fix this problem for all the existing adapters. Having a property, we fill the corresponding `_session' in the base class with the same session which is desired. Moreover, since set/get session is a light weight operation, it makes sense to have it as a property and not a get/set method.

**Comment by andre-merzky** [comment]
Hi Mehdi -- indeed, I think that should work nicely.  Neat! :D   Will you open a pull request toward devel?  I'd be happy to merge that in...

Thanks!

**Comment by mehdisadeghi** [comment]
Good to hear that! Let's fix'em all :)

P.S. I just wanted to add one commit to the PR, but I don't know why there are three commits appearing there.
