### ISSUE TITLE
How to control number of locally executing jobs

### ISSUE THREAD

**Issue by millingw** [radical-cybertools/saga-python#532]
When submitting jobs to localhost and not using a batch system, is there any way within the SAGA configuration to control or limit the number of simultaneously executing jobs? For example, if I submit 200 small local jobs, will the API try to run each job immediately?

**Comment by andre-merzky** [comment]
SAGA is a synchronous API, and when a job run call returns, then it guarantees that the job is, in fact, running.  You will have to do any throttling above the API layer, with something like this:

```
def run_throttled(service, descriptions, throttle=200):
    """
    js: saga.job.Service instance to run the jobs on
    descriptions: list of saga.job.Description instances to run
    throttle: integer, defining max number of jobs to run
    """
    jobs    = list()
    running = list()
    final   = list()

    for d in descriptions:
        jobs.append(js.create_job(d)

    # run first batch of jobs
    for i in range(throttle):
        if not jobs:
            break # nothing to run anymore
        job = jobs.pop(0)
        job.run()
        running.append(job)

    while jobs:
        for job in running:
            if job.state in [saga.job.DONE | FAILED | CANCELED]:
                running.delete(job)
                final.append(job)
                new_job = jobs.pop(0)
                new_job.run()
                running.append(new_job)
                break # avoid recursion over changing list

    for job in running:
        job.wait()
        final.append(job)
        running.delete(job)
```

This is not very elegant, but I hope you see what I mean.  Also its probably wrong (I did not run this, but just sketched it down).  One can create more elaborate and efficient versions based on bulk submission and state notifications though.  The bottom line is: SAGA does not throttle, the application (or the backend) has to do that.

**Comment by millingw** [comment]
Thanks for the clarification - I'm now implementing a local task manager. One thing I've noticed is that if I submit a job through an instance of a local job service and save its jobid, if I then close the job service and try to query the job state through a new instance of a local job service it throws an error. Will local jobs only be reported back correctly from the local service through which they were submitted? 

File "/usr/local/lib/python2.7/dist-packages/saga/attributes.py", line 2629, in __getattr__
    return self._attributes_i_get      (key, flow=self._DOWN)  
File "/usr/local/lib/python2.7/dist-packages/saga/attributes.py", line 1146, in _attributes_i_get
    self._attributes_t_call_getter (key)  
File "/usr/local/lib/python2.7/dist-packages/saga/attributes.py", line 633, in _attributes_t_call_getter
    val=key_getter ()  
File "/usr/local/lib/python2.7/dist-packages/saga/job/job.py", line 607, in get_state
    return self._adaptor.get_state (ttype=ttype)  
File "/usr/local/lib/python2.7/dist-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function  
    return sync_function (self, *args, **kwargs)  
File "/usr/local/lib/python2.7/dist-packages/saga/adaptors/shell/shell_job.py", line 1382, in get_state
    self._update_state (self._adaptor.string_to_state (stats['state']))  
File "/usr/local/lib/python2.7/dist-packages/saga/adaptors/shell/shell_job.py", line 1347, in _update_state  
    self._adaptor.stage_output (self.js.shell, self.jd)  
AttributeError: 'ShellJob' object has no attribute 'jd'

**Comment by andre-merzky** [comment]
Oh, that seems to be a bug!  You should be able to reconnect from a different session - but not all job attributes are then available.  Specifically the original job description will be gone, and this is what this code stumbles over...

**Comment by andre-merzky** [comment]
Would you mind giving the `fix/job_reconnect_532` branch a try?  That should resolve this issue...

**Comment by millingw** [comment]
Yes, that seems to be working now. Thanks!

**Comment by andre-merzky** [comment]
Great - we'll merge that then into the next release!

**Comment by millingw** [comment]
Unrelated to the above issue, I occasionally see the following error appearing at the end of my test run (and after I've called js.close_service() on my local job service)

Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/saga_python-0.40.1-py2.7.egg/saga/adaptors/shell/shell_job.py", line 121, in run
  File "/usr/local/lib/python2.7/dist-packages/radical/utils/url.py", line 76, in __str__
  File "/usr/local/lib/python2.7/dist-packages/radical/utils/contrib/urlparse25.py", line 158, in geturl
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by millingw** [comment]
I've implemented a simple check to monitor how many local jobs are executing:

def running_jobs(self):
        ids = self.js.list()
        count = 0
        for job_id in ids :
            j = self.js.get_job(job_id)
            state = j.get_state()
            if (state == saga.job.RUNNING):
                count += 1
        return count

This works ok, but will likely become slow once there a large number of finished jobs being listed every time. Is there an easy way to purge completed / failed jobs so they are not listed?

**Comment by andre-merzky** [comment]
Right, that will become slow very quickly.  Two answers here:

  - if finalized jobs are purged depends on the backend.  For the shell backend we have some control (but currently not purge as long as the job service instance is alive).  For the batch schedulers, we see very different purging policies on production systems...

 - SAGA does have support for bulk operations, which should make the above more efficient:

```
def running_jobs(self):
    c = saga.job.Container()
    for job in jobs:
        c.add(job)
    states = c.get_states()
    return states.count(saga.job.RUNNING)
```

Now, bulk operations are not yet supported by all adaptors, but we are in the process of adding bulk support on an as-needed basis.  At the moment, bulks work on ssh/fork and condor based submissions.

Further, we would advise to keep job instances around instead of reconnecting based on job-id, if that is possible in your code structure.  Reconnecting can be expensive.  Repeated queries on the same job on the other hand can be implemented more efficiently, for example via state caching.

If you don't mind, please remind me what backends are important for you, and I'll look into the bulking and state query caching support for those.  

Best, Andre.

**Comment by millingw** [comment]
Hi Andre,
I'll try and describe our application - it might better explain what we are trying to do.  
Our application is actually a Django web app. In this, users can select to run a simulation, which itself will create a potentially large number of small tasks. The tasks can be executed locally (ie shell) or on a backend (in our case LSF, although this will change at some future point). A thread in the Django app periodically does the following:  
1) Checks for any new tasks and tries to submit them  
2) Updates the state of any executing jobs, local or remote 
3) Retrieves the output files from any completed job and updates the task status in the Django web app
We dont persist the job service instances between executions of the update thread, primarily due to concerns about ssh connection timeouts. In the case of the local service, we need to query for the number of running jobs so that we stay within a sensible limit. In the case of the remote service, we assume we can send as many as we want and the batch system will queue them sensibly. I'm concerned that we might end up with a large number of inactive jobs being read every time we start the job service, meaning that our solution might not be scaleable. Is there any way that we can manually purge jobs that we are no longer interested in? For example, in the case of the local service, it appears to create the job information in ~/.saga/adaptors/shell_job/<job-id> so could we simply delete these directories while the job service is inactive?

Thanks!

**Comment by andre-merzky** [comment]
The shell adaptor has the ability to purge jobs, see https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/adaptors/shell/shell_job.py#L165 which is implemented in https://github.com/radical-cybertools/saga-python/blob/devel/src/saga/adaptors/shell/shell_wrapper.sh#L1045

As the code comment in the latter says, this can be slow if you have thousands of jobs, but otherwise does not create a significant overhead.  That should actually be turned on by default -- do you see it behaving differently?  Or is the number of jobs growing too large for individual job service instances?  Note though that concurrent job services will also purge final jobs managed by *other* service instances, even if those services are still alive.

For the batch adaptors, some batch systems have the ability to purge on request, some don't.  We usually have the opposite problem, that job info disappear to quickly :P  Are you trying to address a potential future issue, or do you observe actual scaling problems on LSF?

> Will local jobs only be reported back correctly from the local service through which they were submitted?

No, at the moment, all job services going to the same host share state, and thus report on all jobs on that host.  Changing that would make reconnecting to jobs difficult.  But as you experienced, reconnect is not complete anyways: reconnected jobs don't have a job description.  

This can in principle be implemented (jobs could be bound to a specific JS instance), but that would come with a performance impact (which I can't quantify though, might be small).

> Exception in thread Thread-4 (most likely raised during interpreter shutdown):

Yes, we also see those sometimes.  I am not exactly sure if our shutdown is unclean, or if this is caused by the unpredictability of the Python garbage collection.  As far as I can tell (but I did not look too closely, yet), the errors come from objects which are not in use anymore on API level.

**Comment by millingw** [comment]
Hi Andre, thanks for the very clear explanation. I've been through the shell adaptor code and understand what is happening now; the local jobs are indeed being purged after a day by default.

**Comment by andre-merzky** [comment]
considered resolved.
