### ISSUE TITLE
Saga.Session constructor refactor suggestion

### ISSUE THREAD

**Issue by joanlopez** [radical-cybertools/saga-python#555]
Hi,

We are using your library and we've been experiencing problems with the Session class.

The problem is that your implementation of the Session constructor (**init**) is _breaking_ the default and expected behaviour of this function.

It's true that it is well-documented on your documentation/comments, but I think that it is an ugly and a non common-sense design. I'm not an expert Python developer, but I think that when a developer calls the constructor method of a class, he expects having a new instance of the class, not an instance that shares things with previous instances.

For me, a good choice could be changing the default value from True to False, with this change, the functionality will be the same and the usage of this class will be more common-sense.

Many thanks,

Joan

**Comment by andre-merzky** [comment]
Hi Joan, 

I think I see your point.  Changing the default setting though is not something I would agree to lightly, as it is bound to break applications, and (but possibly of lesser importance in this context) would be in disagreement with the spec.

What I would propose though is that the returned session instance is not to *share* state with the default session, but instead gets initialized just like the default session, ie. with a pre-populated (but un-shared) context list.  Would that make sense?

**Comment by joanlopez** [comment]
There are some things that I haven't understood. Which are the main differences between your suggestion and the default behaviour when you pass False as entry parameter?

Maybe with a clearer idea about this fact, then I would be able to determine if it would make sense.

Thanks

**Comment by andre-merzky** [comment]
The `saga.Session` is, conceptually, a container for security credentials, ie. for `saga.Context` instances.  Further, SAGA has a default session instance which is implemented as a global singleton.  That default session is used whenever the application is not explicitly specifying another session instance.  The default session tries to pick up security credentials at the known default locations: `/tmp/x509_<uid>`, `$HOME/.ssh/id_[dr]sa*`, etc.

When creating a new session instance, it would in general (`default=True`) get it initialized with the context list of the default session, so that it is generally usable as-is.  The application is then free to add other contexts as needed.  If `default=False` is passed, then the session instance is empty, and it will not initially manage any contexts.  The application then *needs* to add contexts in order to have a usable session.

IIU your initial issue description correctly, the unexpected behavior is that created session instances by default (`default=True`) *share* the context list with the default session singleton -- changing that context list will also change the list of contexts in the default session.

The proposal is: when creating session instances with `default=True`, we can *copy* the context list from the default session, so that adding contexts to the new session will only change that session instance, but not the default session.  We would then additionally need to expose the default session singleton on the API layer, to allow applications to modify it, but I would find that acceptable, and I think that would not break the majority of applications.

Did that make more sense?  If not, don't hesitate to ask!  If I am off target with interpreting the ticket, I would appreciate clarification on what the perceived problem is.

Best, Andre.

**Comment by joanlopez** [comment]
Many thanks for this more extensive explanation. 

Now, what you said on the previous message take more sense.

I think that the behaviour that you are proposing is which have more common-sense. I'm totally agree with the default session behaviour and its relation with the 'default' entry parameter. What I considered confusing is the context sharing between different instances (not default).

IMHO, with the actual behaviour, you are broking the OO sense of object instances because you are sharing the state between different instances, by default.

For me, you can apply what you've suggested. I will be more happy and I think that It will reduce the number of possible confusing situations by the developers using SAGA.

Many thanks for all the support,

Best,

**Comment by andre-merzky** [comment]
This is now implemented in the `feature/session_ctor` branch, feel free to give it a try.  It exposes an additional `saga.DefaultSession` singleton, the original `saga.Session` class behaves as discussed.

This will probably take a while to trickle into the release -- we first need to make (reasonably) sure that this API change does not break existing code.  But, please, feel free to give it a go and to provide feedback!

**Comment by andre-merzky** [comment]
This has been implemented.
