### ISSUE TITLE
SAGA not compatible with Jupyter/iPython notebooks

### ISSUE THREAD

**Issue by drelu** [radical-cybertools/saga-python#580]
Import of SAGA fails due to issue with logging module:

![screen shot 2016-07-30 at 12 37 43 pm](https://cloud.githubusercontent.com/assets/222015/17271750/9384a426-5652-11e6-97dd-cb37505e3000.png)

Environment:

login1.wrangler ~$ conda --version
conda 4.1.11
login1.wrangler ~$ ipython --version
5.0.0
login1.wrangler ~$ jupyter --version
4.1.0
login1.wrangler ~$ python -c 'import saga; print saga.version'
0.41.3

**Comment by andre-merzky** [comment]
Was the logging module loaded before, or is that implicitly loaded by ipython?  In the first case, please load it after the radical modules.  We need the log fixer in place to get python to behave when creating new processes...

**Comment by drelu** [comment]
It is loaded by iPython. There is no way not to load it.

**Comment by andre-merzky** [comment]
*sigh*  Well, then the radical stack will not be stable under iPython.

The underlying issue is that some python code libraries are not safe to use in threaded environments, as they carry locks across fork calls.  That most prominently pops up in the logging module, but also in other modules.  The log fixer which you stumbled over fixes that by monkey-patching the logging module -- but that only works if logging is not loaded before.

I can change the exception into a warning, of course, but the problem will remain.  As long as you are only using SAGA, you should be safe (assuming you don't use asynchronous SAGA calls, which mostly are implemented via threads).

**Comment by andre-merzky** [comment]
This is now implemented in the radical.utils branch `fix/log_atfork_warning`:

```
(ve)merzky@thinkie:~/radical/radical.utils (fix/log_atfork_warning %=) $ export FOO_VERBOSE=INFO
(ve)merzky@thinkie:~/radical/radical.utils (fix/log_atfork_warning %=) $ python -c 'import logging; import radical.utils as ru; l=ru.get_logger("foo"); l.info("bar")'
/home/merzky/radical/radical.pilot.split_module/ve/local/lib/python2.7/site-packages/radical/utils/atfork/stdlib_fixer.py:58: UserWarning: logging module already imported before fixup.
  warnings.warn('logging module already imported before fixup.')
2016-07-30 23:11:53,756: foo                 : MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.5+ (default, Sep 17 2013, 15:31:50) [GCC 4.8.1]
2016-07-30 23:11:53,756: foo                 : MainProcess                     : MainThread     : INFO    :                      pid: 25297
2016-07-30 23:11:53,756: foo                 : MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2016-07-30 23:11:53,757: foo                 : MainProcess                     : MainThread     : INFO    : bar
```

**Comment by andre-merzky** [comment]
Closing until it pops up again.
