### ISSUE TITLE
fix/issue_1514

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/saga-python#655]
```
https://github.com/radical-cybertools/saga-python/blob/fix/issue_1514/tests/saga_test_example_1514.py#L68
```
the file at line 68 in the folder is not copied.

**Comment by andre-merzky** [comment]
I simplified the example.  Please use always minimal  when showing a problem - otherwise it takes  longer  to dig through what's up.  Also, `assert` is your friend to show expected behavior (and complain where its not met).

The branch now contains fixes for sftp, and the example passes.  Please check if you need any other cases covered!

**Comment by georgeha** [comment]
Thanks Andre. I am going to leave the ticket open until we finish testing this issue.
